In [3]:
import numpy as np
from matplotlib import pyplot as plt

In [23]:
m = np.random.random_sample((4,4))
print(m)

[[0.27898216 0.0121536  0.49427076 0.2410945 ]
 [0.28993797 0.04078793 0.97874521 0.78437522]
 [0.80442909 0.74082944 0.17896672 0.79803122]
 [0.66982234 0.99362451 0.37258146 0.81752081]]
